Repository cahirwpz/demoscene, pull requests merged in 2022-05, with the labels that each got.

#81 Document and refactor the 'floor' effect
  effects/floor/data/floor.png
  effects/floor/data/stripeLight.c
  effects/floor/data/stripeWidth.c
  effects/floor/floor.c
  prototypes/floor_data/.gitignore
  prototypes/floor_data/floor_data.pde
Labels: WiP

#88 Handle read-only filesystem in a unified way
  .gitignore
  Makefile
  a500rom.asm
  build/common.mk
  build/effect.mk
  tools/adfutil.py
  tools/fsutil.py
  tools/romutil.py
Labels: cleanup

#89 Make the filesystem oblivious to device it reads from
  a500rom.asm
  bootloader.asm
  include/common.h
  include/system/boot.h
  include/system/file.h
  include/system/filesys.h
  include/system/floppy.h
  lib/libgfx/CpuEdge.c
  system/amigaos.c
  system/drivers/filesys.c
  system/drivers/floppy.c
  system/drivers/memory-file.c
  system/kernel/amigahunk.c
  system/loader.c
Labels: feature
